version: '2'

services:
  
  dovecot-app:
    image: tiredofit/dovecot
    container_name: dovecot-app
    volumes:
    - ./certs:/assets/certs
    - ./data/vmail:/var/vmail
    - ./data/db:/data
    - ./logs/dovecot:/var/log/dovecot
    environment:

    - ZABBIX_HOSTNAME=dovecot-app
    - HOSTNAME=mail.example.com
    - POSTMASTER=postmaster@mailhost.com

    - AUTH_TYPE=mysql
    - DB_HOST=dovecot-db
    - DB_NAME=mail
    - DB_USER=mail
    - DB_PASS=password

    - LDAP_HOST=ldap-host
    - LDAP_BASE_DN=dc=example,dc=org
    networks:
      - proxy-tier
    restart: always

  dovecot-db:
    image: tiredofit/mariadb
    container_name: dovecot-db
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - ROOT_PASS=rootpassword
      - DB_NAME=mail
      - DB_USER=mail
      - DB_PASS=password

      - ZABBIX_HOSTNAME=dovecot-db

    networks:
      - proxy-tier
    restart: always

networks:
  proxy-tier:
    external:
      name: nginx-proxy

