#!/usr/bin/with-contenv bash

for s in /assets/functions/*; do source $s; done
PROCESS_NAME="dovecot"
output_off
check_container_initialized
check_service_initialized init
liftoff
output_on

print_info "Starting Dovecot"
dovecot -F
